"""Supplies Interface classes to access APIs."""
from bitex.interface.binance import Binance
from bitex.interface.bitfinex import Bitfinex
from bitex.interface.bitstamp import Bitstamp
from bitex.interface.bittrex import Bittrex
from bitex.interface.bleutrade import Bleutrade
from bitex.interface.bter import Bter
from bitex.interface.ccex import CCEX
from bitex.interface.coincheck import CoinCheck
from bitex.interface.cryptopia import Cryptopia
from bitex.interface.hitbtc import HitBTC
from bitex.interface.independentreserve import IndependentReserve
from bitex.interface.kiwicoin import KiwiCoin
from bitex.interface.kraken import Kraken
from bitex.interface.nzbcx import NZBCX
from bitex.interface.okcoin import OKCoin
from bitex.interface.okex import OKEX
from bitex.interface.poloniex import Poloniex
from bitex.interface.quadriga import QuadrigaCX
from bitex.interface.rocktrading import TheRockTrading
from bitex.interface.vaultoro import Vaultoro
from bitex.interface.wex import WEX
